import {
  AssetProductType,
  HQLALevel,
  LiabilityProductType,
  ProductType,
} from '../domain/enums';
import {
  SimulationConfig,
  ProductRiskParameters,
  GlobalSimulationParameters,
  BehaviourParameters,
  ShockParameters,
  ToleranceParameters,
} from '../domain/config';
import { LiquidityTag } from '../domain/liquidity';

const productParameters: Record<ProductType, ProductRiskParameters> = {
  [AssetProductType.DerivativeAssets]: { productType: AssetProductType.DerivativeAssets, riskWeight: 1, baseDefaultRate: 0, lossGivenDefault: 0, volumeElasticityToRate: 0 },
  [LiabilityProductType.DerivativeLiabilities]: { productType: LiabilityProductType.DerivativeLiabilities, riskWeight: 0, baseDefaultRate: 0, lossGivenDefault: 0, volumeElasticityToRate: 0 },
  [LiabilityProductType.CreditProvisions]: { productType: LiabilityProductType.CreditProvisions, riskWeight: 0, baseDefaultRate: 0, lossGivenDefault: 0, volumeElasticityToRate: 0 },
  [AssetProductType.CashReserves]: {
    productType: AssetProductType.CashReserves,
    riskWeight: 0,
    baseDefaultRate: 0.0,
    lossGivenDefault: 0,
    volumeElasticityToRate: 0,
  },
  [AssetProductType.Gilts]: {
    productType: AssetProductType.Gilts,
    riskWeight: 0,
    baseDefaultRate: 0.0005,
    lossGivenDefault: 0.1,
    volumeElasticityToRate: 0,
  },
  [AssetProductType.Mortgages]: {
    productType: AssetProductType.Mortgages,
    riskWeight: 0.35,
    baseDefaultRate: 0.004,
    lossGivenDefault: 0.25,
    volumeElasticityToRate: -0.4,
    adverseSelectionRatePremiumThreshold: 0.004,
    adverseSelectionPdSlope: 18,
    adverseSelectionMaxMultiplier: 2.2,
    loan: {
      defaultTermMonths: 360,
      maxTermMonths: 420,
      initialSeasoningEnabled: true,
      initialCouponDispersionBps: 50,
      initialPdMultiplierRange: { min: 0.8, max: 1.25 },
      initialLgdMultiplierRange: { min: 0.9, max: 1.1 },
      initialMinBucketOutstanding: 1e6,
    },
  },
  [AssetProductType.CorporateLoans]: {
    productType: AssetProductType.CorporateLoans,
    riskWeight: 1.0,
    baseDefaultRate: 0.015,
    lossGivenDefault: 0.45,
    volumeElasticityToRate: -0.3,
    adverseSelectionRatePremiumThreshold: 0.005,
    adverseSelectionPdSlope: 14,
    adverseSelectionMaxMultiplier: 2.5,
    loan: {
      defaultTermMonths: 60,
      maxTermMonths: 420,
      initialSeasoningEnabled: true,
      initialCouponDispersionBps: 75,
      initialPdMultiplierRange: { min: 0.85, max: 1.4 },
      initialLgdMultiplierRange: { min: 0.9, max: 1.15 },
      initialMinBucketOutstanding: 1e6,
    },
  },
  [AssetProductType.ReverseRepo]: {
    productType: AssetProductType.ReverseRepo,
    riskWeight: 0,
    baseDefaultRate: 0.0,
    lossGivenDefault: 0,
    volumeElasticityToRate: 0,
  },
  [LiabilityProductType.RetailDeposits]: {
    productType: LiabilityProductType.RetailDeposits,
    riskWeight: 0,
    baseDefaultRate: 0.0,
    lossGivenDefault: 0,
    volumeElasticityToRate: 0.5,
  },
  [LiabilityProductType.CorporateDeposits]: {
    productType: LiabilityProductType.CorporateDeposits,
    riskWeight: 0,
    baseDefaultRate: 0.0,
    lossGivenDefault: 0,
    volumeElasticityToRate: 0.8,
  },
  [LiabilityProductType.RetailTransactionalDeposits]: {
    productType: LiabilityProductType.RetailTransactionalDeposits,
    riskWeight: 0,
    baseDefaultRate: 0.0,
    lossGivenDefault: 0,
    volumeElasticityToRate: 0.25,
  },
  [LiabilityProductType.RetailSavingsDeposits]: {
    productType: LiabilityProductType.RetailSavingsDeposits,
    riskWeight: 0,
    baseDefaultRate: 0.0,
    lossGivenDefault: 0,
    volumeElasticityToRate: 0.55,
  },
  [LiabilityProductType.CorporateOperatingDeposits]: {
    productType: LiabilityProductType.CorporateOperatingDeposits,
    riskWeight: 0,
    baseDefaultRate: 0.0,
    lossGivenDefault: 0,
    volumeElasticityToRate: 0.65,
  },
  [LiabilityProductType.CorporateNonOperatingDeposits]: {
    productType: LiabilityProductType.CorporateNonOperatingDeposits,
    riskWeight: 0,
    baseDefaultRate: 0.0,
    lossGivenDefault: 0,
    volumeElasticityToRate: 1.0,
  },
  [LiabilityProductType.WholesaleFundingST]: {
    productType: LiabilityProductType.WholesaleFundingST,
    riskWeight: 0,
    baseDefaultRate: 0.0,
    lossGivenDefault: 0,
    volumeElasticityToRate: 0,
  },
  [LiabilityProductType.WholesaleFundingLT]: {
    productType: LiabilityProductType.WholesaleFundingLT,
    riskWeight: 0,
    baseDefaultRate: 0.0,
    lossGivenDefault: 0,
    volumeElasticityToRate: 0,
  },
  [LiabilityProductType.RepurchaseAgreements]: {
    productType: LiabilityProductType.RepurchaseAgreements,
    riskWeight: 0,
    baseDefaultRate: 0.0,
    lossGivenDefault: 0,
    volumeElasticityToRate: 0,
  },
};

const liquidityTags: Record<ProductType, LiquidityTag> = {
  [AssetProductType.DerivativeAssets]: { productType: AssetProductType.DerivativeAssets, hqlaLevel: HQLALevel.None, lcrInflowRate: 0, nsfrRsfFactor: 1 },
  [LiabilityProductType.DerivativeLiabilities]: { productType: LiabilityProductType.DerivativeLiabilities, hqlaLevel: HQLALevel.None, lcrOutflowRate: 0, nsfrAsfFactor: 0 },
  [LiabilityProductType.CreditProvisions]: { productType: LiabilityProductType.CreditProvisions, hqlaLevel: HQLALevel.None, lcrOutflowRate: 0, nsfrAsfFactor: 0 },
  [AssetProductType.CashReserves]: {
    productType: AssetProductType.CashReserves,
    hqlaLevel: HQLALevel.Level1,
    lcrInflowRate: 0,
    nsfrRsfFactor: 0,
  },
  [AssetProductType.Gilts]: {
    productType: AssetProductType.Gilts,
    hqlaLevel: HQLALevel.Level1,
    lcrInflowRate: 0,
    nsfrRsfFactor: 0,
  },
  [AssetProductType.Mortgages]: {
    productType: AssetProductType.Mortgages,
    hqlaLevel: HQLALevel.None,
    lcrInflowRate: 0.05,
    nsfrRsfFactor: .65,
  },
  [AssetProductType.CorporateLoans]: {
    productType: AssetProductType.CorporateLoans,
    hqlaLevel: HQLALevel.None,
    lcrInflowRate: 0.05,
    nsfrRsfFactor: .85,
  },
  [AssetProductType.ReverseRepo]: {
    productType: AssetProductType.ReverseRepo,
    hqlaLevel: HQLALevel.None,
    lcrInflowRate: 0,
    nsfrRsfFactor: 0,
  },
  [LiabilityProductType.RetailDeposits]: {
    productType: LiabilityProductType.RetailDeposits,
    hqlaLevel: HQLALevel.None,
    lcrOutflowRate: 0.05,
    nsfrAsfFactor: 0.95,
  },
  [LiabilityProductType.CorporateDeposits]: {
    productType: LiabilityProductType.CorporateDeposits,
    hqlaLevel: HQLALevel.None,
    lcrOutflowRate: 0.4,
    nsfrAsfFactor: 0.5,
  },
  [LiabilityProductType.RetailTransactionalDeposits]: {
    productType: LiabilityProductType.RetailTransactionalDeposits,
    hqlaLevel: HQLALevel.None,
    lcrOutflowRate: .05,
    nsfrAsfFactor: .95,
  },
  [LiabilityProductType.RetailSavingsDeposits]: {
    productType: LiabilityProductType.RetailSavingsDeposits,
    hqlaLevel: HQLALevel.None,
    lcrOutflowRate: .1,
    nsfrAsfFactor: .9,
  },
  [LiabilityProductType.CorporateOperatingDeposits]: {
    productType: LiabilityProductType.CorporateOperatingDeposits,
    hqlaLevel: HQLALevel.None,
    lcrOutflowRate: .25,
    nsfrAsfFactor: .5,
  },
  [LiabilityProductType.CorporateNonOperatingDeposits]: {
    productType: LiabilityProductType.CorporateNonOperatingDeposits,
    hqlaLevel: HQLALevel.None,
    lcrOutflowRate: .4,
    nsfrAsfFactor: .5,
  },
  [LiabilityProductType.WholesaleFundingST]: {
    productType: LiabilityProductType.WholesaleFundingST,
    hqlaLevel: HQLALevel.None,
    lcrOutflowRate: 1.0,
    nsfrAsfFactor: 0.0,
  },
  [LiabilityProductType.WholesaleFundingLT]: {
    productType: LiabilityProductType.WholesaleFundingLT,
    hqlaLevel: HQLALevel.None,
    lcrOutflowRate: 0.0,
    nsfrAsfFactor: 1.0,
  },
  [LiabilityProductType.RepurchaseAgreements]: {
    productType: LiabilityProductType.RepurchaseAgreements,
    hqlaLevel: HQLALevel.None,
    lcrOutflowRate: 0,
    nsfrAsfFactor: 0.0,
  },
};

const global: GlobalSimulationParameters = {
  taxRate: 0.25,
  operatingCostRatio: 0.02,
  maxDepositGrowthPerStep: 0.08,
  maxLoanGrowthPerStep: 0.05,
  fixedOperatingCostPerMonth: 0.05e9,
  initialPortfolioSeed: 123456789,
  competitorDepositReactionSpeed: 0.12,
  competitorCorporateDepositReactionSpeed: 0.16,
  competitorMortgageReactionSpeed: 0.08,
  competitorCorporateLoanSpreadReactionSpeed: 0.1,
  competitorReactionStressBoost: 0.9,
  competitorReactionMeanReversion: 0.03,
};

const riskLimits = {
  minCet1Ratio: 0.045,
  minTier1Ratio: 0.06,
  minTotalCapitalRatio: 0.08,
  minLeverageRatio: 0.0325,
  minLcr: 1.0,
  minNsfr: 1.0,
  // Report-alignment add-ons so opening RWA is closer to Metro 2024 disclosure table.
  rwaAddOns: {
    operationalRisk: 0.72e9,
    otherAdjustments: 0.05325e9,
  },
  capitalBufferStack: {
    conservationBuffer: 0.025,
    countercyclicalBuffer: 0.02,
    systemicBuffer: 0,
    // Remove opening management add-on so sandbox starts closer to Metro baseline.
    managementBuffer: 0,
  },
  capitalPolicy: {
    defaultDividendPayoutRatio: 0.3,
    at1CouponRateAnnual: 0.08,
    at1DiscretionaryCet1Threshold: 0.125,
    internalTargetBaseBuffer: 0.005,
    internalTargetVolatilitySensitivity: 0.004,
    internalTargetStressSensitivity: 0.006,
    internalTargetConfidenceSensitivity: 0.004,
    internalTargetConductSensitivity: 0.003,
    internalTargetMaxBuffer: 0.03,
    payoutRestrictionSlope: 0.04,
    at1InternalTargetHeadroom: 0.005,
  },
  concentration: {
    maxSingleSectorShare: 0.45,
    maxSingleGeographyShare: 0.4,
  },
  boardPressure: {
    earningsVolatilityTolerance: 0.6e9,
    franchiseTarget: 0.75,
    riskAppetiteCet1Headroom: 0.02,
  },
};

const behaviour: BehaviourParameters = {
  depositBaselineGrowthMonthly: 0.002,
  loanBaselineGrowthMonthly: 0,
  minDepositGrowthPerStep: -0.1,
  minLoanGrowthPerStep: -0.02,
  loanFeeRateMonthly: 0.001,
  horizonRiskPenaltyWeight: 0.35,
  depositByProduct: {
    [LiabilityProductType.RetailTransactionalDeposits]: {
      baselineGrowthMonthly: 0.0018,
      baseChurnMonthly: 0.0035,
      policyRateBeta: 0.12,
      competitorSensitivity: 0.55,
      passThroughLag: 0.45,
      underpricingConvexity: 20,
      underpricingDurationSensitivity: 0.08,
      franchiseDecayRate: 0.5,
      franchiseRecoveryRate: 0.04,
      reacquisitionDrag: 0.35,
      stabilityDecayRate: 0.5,
      stabilityRecoveryRate: 0.06,
      mixMigrationRate: 0.04,
      mixMigrationDurationSensitivity: 0.06,
    },
    [LiabilityProductType.RetailSavingsDeposits]: {
      baselineGrowthMonthly: 0.0024,
      baseChurnMonthly: 0.002,
      policyRateBeta: 0.2,
      competitorSensitivity: 0.85,
      passThroughLag: 0.7,
      underpricingConvexity: 26,
      underpricingDurationSensitivity: 0.1,
      franchiseDecayRate: 0.58,
      franchiseRecoveryRate: 0.05,
      reacquisitionDrag: 0.45,
      stabilityDecayRate: 0.62,
      stabilityRecoveryRate: 0.05,
      mixMigrationRate: 0.06,
      mixMigrationDurationSensitivity: 0.08,
    },
    [LiabilityProductType.CorporateOperatingDeposits]: {
      baselineGrowthMonthly: 0.0012,
      baseChurnMonthly: 0.0045,
      policyRateBeta: 0.1,
      competitorSensitivity: 0.95,
      passThroughLag: 0.4,
      underpricingConvexity: 28,
      underpricingDurationSensitivity: 0.14,
      franchiseDecayRate: 0.62,
      franchiseRecoveryRate: 0.03,
      reacquisitionDrag: 0.5,
      stabilityDecayRate: 0.58,
      stabilityRecoveryRate: 0.05,
      mixMigrationRate: 0.09,
      mixMigrationDurationSensitivity: 0.1,
    },
    [LiabilityProductType.CorporateNonOperatingDeposits]: {
      baselineGrowthMonthly: 0.0008,
      baseChurnMonthly: 0.0075,
      policyRateBeta: 0.08,
      competitorSensitivity: 1.2,
      passThroughLag: 0.25,
      underpricingConvexity: 32,
      underpricingDurationSensitivity: 0.18,
      franchiseDecayRate: 0.7,
      franchiseRecoveryRate: 0.02,
      reacquisitionDrag: 0.6,
      stabilityDecayRate: 0.7,
      stabilityRecoveryRate: 0.03,
      mixMigrationRate: 0.12,
      mixMigrationDurationSensitivity: 0.12,
    },
  },
  loanPipelineByProduct: {
    [AssetProductType.Mortgages]: {
      baseDemandRateMonthly: 0.0075,
      pricingSensitivity: 2.4,
      macroSensitivity: 1.2,
      baseApprovalRate: 0.82,
      underwritingSensitivity: 0.5,
      drawdownRateMonthly: 0.45,
      cancellationRateMonthly: 0.08,
    },
    [AssetProductType.CorporateLoans]: {
      baseDemandRateMonthly: 0.009,
      pricingSensitivity: 1.9,
      macroSensitivity: 1.8,
      baseApprovalRate: 0.68,
      underwritingSensitivity: 0.65,
      drawdownRateMonthly: 0.5,
      cancellationRateMonthly: 0.12,
    },
  },
  creditRiskDynamics: {
    adverseSelection: {
      renewalShareMonthly: 0.08,
      renewalEligibilityMonths: 12,
      renewalRatePremiumThreshold: 0.004,
      renewalPdSlope: 20,
      renewalMaxMultiplier: 2.8,
      underwritingInteractionWeight: 1.1,
      selectionPressureEventThreshold: 0.03,
    },
    affordabilityByProduct: {
      [AssetProductType.Mortgages]: {
        baselineDriftMonthly: 0.002,
        couponGapSensitivity: 4.0,
        policyRateSensitivity: 0.7,
        unemploymentSensitivity: 3.0,
        gdpContractionSensitivity: 12.0,
        recoverySpeedMonthly: 0.06,
        pdStressSlope: 0.9,
        minIndex: 0.75,
        maxIndex: 2.5,
        resetShareOnRenewal: 0.35,
      },
      [AssetProductType.CorporateLoans]: {
        baselineDriftMonthly: 0.003,
        couponGapSensitivity: 3.2,
        policyRateSensitivity: 0.5,
        unemploymentSensitivity: 3.8,
        gdpContractionSensitivity: 16.0,
        recoverySpeedMonthly: 0.05,
        pdStressSlope: 1.2,
        minIndex: 0.7,
        maxIndex: 3.0,
        resetShareOnRenewal: 0.25,
      },
    },
    refinanceByProduct: {
      [AssetProductType.Mortgages]: {
        minSeasoningMonths: 12,
        basePrepayRateMonthly: 0.004,
        incentiveSensitivity: 9.0,
        riskSelectivity: 0.65,
        minPrepayRateMonthly: 0.001,
        maxPrepayRateMonthly: 0.02,
      },
      [AssetProductType.CorporateLoans]: {
        minSeasoningMonths: 6,
        basePrepayRateMonthly: 0.0025,
        incentiveSensitivity: 6.5,
        riskSelectivity: 0.5,
        minPrepayRateMonthly: 0.0005,
        maxPrepayRateMonthly: 0.015,
      },
    },
    workoutPipeline: {
      baseResolutionLagMonths: 8,
      stressLagSensitivity: 10,
      baseRecoveryRateFloor: 0.15,
      macroRecoveryPenaltySensitivity: 2.2,
      concentrationRecoveryPenaltySensitivity: 0.35,
    },
  },
  costModel: {
    fixedCostPerMonth: 0.05e9,
    servicingCostRateAnnual: 0.0065,
    originationCostRate: 0.01,
    workoutCostRateOnDefaults: 0.035,
  },
  fundingLadder: {
    stRefinanceTenorMonths: 6,
    ltRefinanceTenorMonths: 36,
    rolloverAccessBase: 0.95,
    rolloverAccessMin: 0.45,
    spreadSensitivity: 12,
    liquidityStressPenalty: 0.18,
    franchiseSpreadSensitivity: 0.012,
    capitalSpreadSensitivity: 0.08,
    confidenceSpreadSensitivity: 0.03,
    accessCliffMidpoint: 0.4,
    accessCliffSlope: 6.5,
    accessFloorMultiplier: 0.55,
  },
  ifrs9: {
    sicrPdMultiplierThreshold: 1.75,
    eclScenarios: [{ weight: .2, pdMultiplier: .75 }, { weight: .6, pdMultiplier: 1 }, { weight: .2, pdMultiplier: 1.5 }],
  },
  liquidityDynamics: {
    recessionDepositOutflowMultiplier: 1.25,
    franchiseRunoffSensitivity: 0.35,
    reputationRunoffSensitivity: 0.25,
    recessionInflowHaircut: 0.85,
    recessionAsfPenalty: 0.9,
    depositQualityRunoffSensitivity: 0.45,
    depositQualityAsfPenalty: 0.3,
    multiplierFloor: 0.7,
    multiplierCap: 2.5,
  },
  irrbb: {
    baseAssetDurationYears: 3.2,
    baseLiabilityDurationYears: 1.6,
    hedgeCarrySpread: 0,
  },
  securitiesAccounting: {
    defaultClassificationByProduct: {
      [AssetProductType.Gilts]: 'FVOCI',
    },
    effectiveDurationYearsByProduct: {
      [AssetProductType.Gilts]: 5.5,
    },
    fvociCet1InclusionRate: 0.85,
  },
  concentration: {
    stressActivationPdMultiplier: 1.15,
    sectorPdMultiplierByStress: {
      retailMortgage: 1.05,
      commercialRealEstate: 1.3,
      sme: 1.2,
      largeCorporate: 1.1,
      other: 1.1,
    },
    geographyPdMultiplierByStress: {
      london: 1.08,
      south: 1.05,
      midlands: 1.12,
      north: 1.15,
      scotland: 1.1,
      wales: 1.1,
      northernIreland: 1.1,
      other: 1.1,
    },
  },
  boardPressure: {
    earningsVolatilitySmoothing: 0.75,
    volatilityWeight: 0.4,
    franchiseWeight: 0.3,
    riskWeight: 0.3,
    payoutRestraintWeight: 0.15,
  },
  confidenceStateMachine: {
    strongMinScore: 0.8,
    stableMinScore: 0.6,
    watchMinScore: 0.38,
    hardLcrWatch: 1.02,
    hardLcrStressed: 0.92,
    hardNsfrWatch: 1.0,
    hardNsfrStressed: 0.94,
    hardCet1HeadroomWatch: 0.005,
    hardCet1HeadroomStressed: -0.005,
    upgradeSustainMonths: 3,
    impacts: {
      strong: {
        spreadPenaltyBps: -5,
        accessMultiplier: 1,
        equityIssuanceMultiplier: 1,
        equityIssuanceFeeRate: 0.005,
      },
      stable: {
        spreadPenaltyBps: 0,
        accessMultiplier: 0.95,
        equityIssuanceMultiplier: 0.9,
        equityIssuanceFeeRate: 0.01,
      },
      watch: {
        spreadPenaltyBps: 35,
        accessMultiplier: 0.75,
        equityIssuanceMultiplier: 0.65,
        equityIssuanceFeeRate: 0.025,
      },
      stressed: {
        spreadPenaltyBps: 120,
        accessMultiplier: 0.45,
        equityIssuanceMultiplier: 0.35,
        equityIssuanceFeeRate: 0.05,
      },
    },
  },
  conductRisk: {
    depositUnderpricingThreshold: 0.01,
    lendingOverpricingThreshold: 0.015,
    depositWeight: 0.55,
    lendingWeight: 0.45,
    underwritingAmplifier: 0.4,
    scoreBuildRate: 0.18,
    scoreDecayRate: 0.06,
    eventProbabilityBase: 0,
    eventProbabilitySlope: 0.06,
    eventProbabilityCap: 0.2,
    eventCooldownMonths: 6,
    fineRateOnRwa: 0.0012,
    remediationRateOnIncome: 0.5,
    minEventCost: 25e6,
    franchiseHit: 0.06,
    reputationHit: 0.08,
  },
  sharePriceModel: {
    peNeutral: 8,
    peMin: 3,
    peMax: 16,
    peScoreSensitivity: 0.8,
    pbNeutral: 0.8,
    pbMin: 0.2,
    pbMax: 1.8,
    pbScoreSensitivity: 0.9,
    earningsValuationWeight: 0.45,
    bookValuationWeight: 0.55,
    meanReversionSpeedMonthly: 0.28,
    maxMonthlyMove: 0.18,
    epsSmoothingMonthly: 0.25,
    epsFloor: 0.02,
    priceFloor: 0.05,
    costOfEquity: 0.12,
    profitabilityWeight: 0.45,
    capitalWeight: 0.25,
    macroWeight: 0.2,
    franchiseWeight: 0.1,
    roeScale: 0.08,
    capitalCet1Scale: 0.05,
    capitalLeverageScale: 0.02,
    macroGdpScale: 0.002,
    macroUnemploymentNeutral: 0.045,
    macroUnemploymentScale: 0.03,
    macroCreditSpreadNeutral: 0.012,
    macroCreditSpreadScale: 0.01,
    franchiseNeutral: 0.6,
    franchiseScale: 0.25,
    capitalBreachDiscount: 0.35,
    failurePriceFactor: 0.25,
    equityIssuanceDiscount: 0.1,
  },
};

const shockParameters: ShockParameters = {
  idiosyncraticRun: {
    baseRunOffRate: 0.1,
    incrementalRate: 0.1,
    maxRunOffRate: 0.5,
  },
};

const tolerances: ToleranceParameters = {
  cashFlowRoundingTolerance: 1e-2,
  cashFlowBreachThreshold: 1,
};

const featureFlags = {
  depositSegmentation: true,
  loanPipeline: true,
  costDecomposition: true,
  fundingLadder: true,
  ifrs9Staging: true,
  liquidityDynamics: true,
  irrbbHedges: true,
  securitiesAccounting: true,
  capitalPolicy: true,
  concentrationRisk: true,
  boardPressure: true,
  confidenceStateMachine: true,
  conductRisk: true,
  recommendations: true,
  stepDiagnosticsAttribution: true,
};

export const baseConfig: SimulationConfig = {
  version: 'v1',
  productParameters,
  liquidityTags,
  global,
  riskLimits,
  behaviour,
  shockParameters,
  tolerances,
  featureFlags,
};
