import { useState } from 'react';
import { BankState } from '../domain/bankState';
import { BoardDecision, boardDecisions, mandateProgress, quarterlyReviews } from '../game/boardroom';
import { customerDeposits, periodHistory } from '../game/management';
import { formatCurrency, formatPct, formatSignedPct } from '../utils/formatters';
interface Props { state: BankState; history: BankState[]; selected: string[]; hasErrors: boolean; onDecision: (d: BoardDecision) => void; onPlan: () => void; onNavigate: (tab: string) => void; }
export default function Boardroom({state:s,history,selected,hasErrors,onDecision,onPlan,onNavigate}:Props) {
 const [period,setPeriod]=useState(3);
 const [lens,setLens]=useState<'Customers'|'Earnings'|'Resilience'>('Customers');
 const periods=periodHistory(history,period), latest=periods.at(-1), prior=periods.at(-2), m=s.risk.riskMetrics;
 const progress=mandateProgress(history), reviews=quarterlyReviews(history);
 const depositChange=customerDeposits(s)/Math.max(1,customerDeposits(history[0]))-1;
 const info={Customers:{value:formatCurrency(customerDeposits(s)),label:'Customer deposits',detail:`${formatSignedPct(depositChange)} since opening. Your offer affects retention; the interest bill affects profit.`,tab:'Loans'},Earnings:{value:formatCurrency(latest?.profit??0),label:`${period===3?'Quarter':'Year'} profit${latest&&latest.months<period?' to date':''}`,detail:'After interest, operating costs, impairment and tax. Retained earnings provide room to grow.',tab:'Accounts'},Resilience:{value:formatPct(m.cet1Ratio),label:'CET1 capital ratio',detail:`${formatPct(m.cet1Requirement)} including combined buffers. Current ratios are never averaged or smoothed.`,tab:'Regulatory'}}[lens];
 return <div className="boardroom city-management">
  <section className="city-viewport" aria-label="City of London bank headquarters">
   <div className="city-title"><span className="scene-kicker">CITY OF LONDON · HEADQUARTERS</span><h1>Your bank. The long view.</h1><p>Set the policy. Let the quarters unfold.</p></div>
   <div className="city-lenses" aria-label="Bank information layers">{(['Customers','Earnings','Resilience'] as const).map(l=><button key={l} aria-pressed={lens===l} className={lens===l?'active':''} onClick={()=>setLens(l)}>{l}</button>)}</div>
   <div className="city-inspector"><small>{info.label}</small><strong>{info.value}</strong><p>{info.detail}</p><button className="button scene-secondary" onClick={()=>lens==='Customers'?onPlan():onNavigate(info.tab)}>Inspect {lens.toLowerCase()} →</button></div>
   <div className="city-location">Threadneedle Street · Strategy persists while time runs</div>
  </section>
  <div className="board-kpis">{[
    {label:latest&&latest.months<period?`${period===3?'Quarter':'Year'} profit to date`:`${period===3?'Quarterly':'Annual'} profit`,value:formatCurrency(latest?.profit??0),detail:latest?`${latest.months} of ${period} months recorded`:'Advance time to start your history',tab:'Accounts'},
    {label:'Customer deposits',value:formatCurrency(customerDeposits(s)),detail:`${formatSignedPct(depositChange)} since opening`,tab:'Overview'},
    {label:'Capital headroom',value:formatSignedPct(m.internalCet1Headroom),detail:'Above / below internal CET1 target',tab:'Regulatory'},
    {label:'Liquidity coverage',value:formatPct(m.lcr),detail:'Current position · 100% minimum',tab:'Regulatory'},
  ].map(k=><button className="board-kpi" key={k.label} onClick={()=>onNavigate(k.tab)}><span>{k.label} ↗</span><strong>{k.value}</strong><small>{k.detail}</small></button>)}</div>
  {hasErrors&&<p role="alert" className="alert danger">Your plan has an invalid input. Open Departments to correct it before advancing time.</p>}
  <div className="management-grid"><section className="card history-card"><div className="section-heading"><div><div className="eyebrow">The bank you are building</div><h2>Watch the strategy develop</h2></div><div className="department-tabs">{[3,12].map(n=><button className={`button ${period===n?'primary':''}`} key={n} aria-pressed={period===n} onClick={()=>setPeriod(n)}>{n===3?'Quarters':'Years'}</button>)}</div></div>
   {periods.length===0?<div className="history-empty"><strong>Your story starts here.</strong><p>Choose a policy below, then run a quarter. You will see earnings accumulate and the funding base develop. You can pause after any month.</p></div>:<><div className="profit-timeline" aria-label="Profit by reporting period">{periods.slice(-12).map(p=><div className="profit-period" key={p.label}><span>{formatCurrency(p.profit)}</span><div className="profit-track"><div className={p.profit<0?'negative':''} style={{height:`${Math.max(4,Math.abs(p.profit)/Math.max(1,...periods.slice(-12).map(x=>Math.abs(x.profit)))*60)}px`}}/></div><strong>{p.label}</strong><small>{p.months<period?`${p.months}/${period} months`:'Complete'}</small></div>)}</div><p className="muted">{latest&&latest.months<period?'The current period is incomplete. Compare it with a full period only after the books close.':prior?`Profit changed by ${formatCurrency(latest!.profit-prior.profit)} from the previous period.`:'Your first completed period establishes the baseline.'}</p>
   <details><summary>View period figures and closing balances</summary><div className="table-scroll"><table className="data-table"><thead><tr><th>Period</th><th>Months</th><th>Profit</th><th>Deposits</th><th>CET1</th></tr></thead><tbody>{periods.map(p=><tr key={p.label}><td>{p.label}</td><td>{p.months}/{period}</td><td>{formatCurrency(p.profit)}</td><td>{formatCurrency(p.deposits)}</td><td>{formatPct(p.cet1)}</td></tr>)}</tbody></table></div></details></>}
  </section><aside className="card management-guide"><div className="eyebrow">How the bank works</div><h2>Follow the consequences</h2><button onClick={onPlan}><strong>1 · Attract funding</strong><span>Deposit offers → customers → interest expense</span></button><button onClick={()=>onNavigate('Loans')}><strong>2 · Put money to work</strong><span>Approvals → drawdowns → earning assets</span></button><button onClick={()=>onNavigate('Accounts')}><strong>3 · Earn and absorb losses</strong><span>Margin − costs − impairment → profit</span></button><button onClick={()=>onNavigate('Regulatory')}><strong>4 · Build capacity</strong><span>Retained profit → capital → sustainable growth</span></button><p className="muted">New lending takes time. Old loans carry the consequences of earlier decisions.</p></aside></div>
  <section className="card"><div className="section-heading"><div><div className="eyebrow">Choose your direction</div><h2>Standing policies & exceptional decisions</h2></div><button className="button" onClick={onPlan}>Open departments →</button></div><p className="muted">These are concrete policy changes, not free bonuses. Review the trade-off before adopting a proposal.</p><div className="strategy-list">{boardDecisions(s).map(d=><details key={d.id} className={selected.includes(d.id)?'selected':''}><summary><span><small>{d.voice}</small><strong>{d.title}</strong></span><span>{selected.includes(d.id)?'In your plan ✓':'Review →'}</span></summary><p>{d.pitch}</p><p><strong>Benefit:</strong> {d.benefit}</p><p><strong>Trade-off:</strong> {d.tradeoff}</p><button className="button primary" disabled={s.status.hasFailed} onClick={()=>onDecision(d)}>Adopt proposal</button></details>)}</div></section>
  <details className="card"><summary>Optional first-year board challenges · {progress.stars}/3 stars</summary><p>The bank continues after year one. These badges record your opening year without changing money or capital.</p><div className="quarterly-reviews">{reviews.map(r=><article key={r.quarter}><strong>Q{r.quarter} · {r.title}</strong><p>{r.detail}</p><span>{r.complete?r.earned?'★ Earned':'Missed':r.active?'In progress':'Upcoming'}</span></article>)}</div>{progress.objectives.map(o=><p key={o.label}>{o.achieved?'✓':'○'} {o.label}: {o.detail}</p>)}</details>
 </div>;
}
