import { BankState } from '../domain/bankState';
import { SimulationConfig } from '../domain/config';
import { BalanceSheetSide, AssetProductType } from '../domain/enums';
import { eligibleCet1, centralBankExclusion, committedExposure } from '../engine/prudential';
import { hedgeExposures } from '../engine/hedgeValuation';
import { formatCurrency, formatPct } from '../utils/formatters';
import TimeSeriesChart from './TimeSeriesChart';

export function leverageDashboardData(state:BankState,config:SimulationConfig) {
 const assets=state.financial.balanceSheet.items.filter(i=>i.side===BalanceSheetSide.Asset);
 const book=assets.reduce((n,i)=>n+i.balance,0);
 const derivativeBook=assets.find(i=>i.productType===AssetProductType.DerivativeAssets)?.balance??0;
 const derivatives=hedgeExposures(state).leverage,reserves=centralBankExclusion(state),commitments=committedExposure(state)*.2;
 const exposure=book-derivativeBook+derivatives-reserves+commitments;
 const cet1=eligibleCet1(state,config),at1=state.financial.capital.at1,tier1=cet1+at1;
 const minimum=config.riskLimits.minLeverageRatio;
 const target=Math.max(minimum,state.behaviour.riskAppetite?.leverage??minimum*1.05);
 return {cet1,at1,tier1,exposure,minimum,target,ratio:exposure>0?tier1/exposure:NaN,required:exposure*minimum,surplus:tier1-exposure*minimum,limit:minimum>0?Math.max(0,tier1/minimum):NaN,
  exposureRows:[{label:'On-balance-sheet assets',value:book},{label:'Remove derivative book assets',value:-derivativeBook},{label:'Add prudential derivative exposure',value:derivatives},{label:'Eligible central bank reserves exclusion',value:-reserves},{label:'Undrawn commitments × 20% CCF',value:commitments}],
 };
}
const signedMoney=(n:number)=>Number.isFinite(n)?`${n<0?'−':'+'}${formatCurrency(Math.abs(n))}`:'N/A';
const pp=(n:number)=>Number.isFinite(n)?`${n<0?'':'+'}${(n*100).toFixed(2)}pp`:'N/A';
function Gauge({actual,required,target,money=false}:{actual:number;required:number;target?:number;money?:boolean}) {
 const max=Math.max(money?1:.06,Number.isFinite(actual)?Math.max(0,actual)*1.2:0,Number.isFinite(required)?required*1.2:0,target??0);
 const x=(n:number)=>8+384*Math.max(0,n)/max;
 return <svg className="capital-bullet" viewBox="0 0 400 65" role="img" aria-label={`Actual ${money?formatCurrency(actual):formatPct(actual)}; threshold ${money?formatCurrency(required):formatPct(required)}`}><rect x="8" y="12" width="384" height="18" rx="5" fill="var(--border)"/><rect x="8" y="12" width={Number.isFinite(actual)?x(actual)-8:0} height="18" rx="5" fill="currentColor"/>{Number.isFinite(required)&&<path d={`M${x(required)} 6v29`} stroke="var(--text)" strokeWidth="3"/>}{target!==undefined&&Number.isFinite(target)&&<path d={`M${x(target)} 6v29`} stroke="#b24b92" strokeWidth="2" strokeDasharray="2 3"/>}{[0,1,2,3,4].map(i=><text key={i} x={8+i*96} y="55" textAnchor={i===0?'start':i===4?'end':'middle'}>{money?`${(max*i/4/1e9).toFixed(1)}bn`:formatPct(max*i/4,1)}</text>)}</svg>;
}
export default function LeverageDashboard({state,config,history}:{state:BankState;config:SimulationConfig;history:BankState[]}) {
 const d=leverageDashboardData(state,config),gap=d.ratio-d.minimum;
 const status=!Number.isFinite(d.ratio)?'Unavailable':gap>=0?'Meets requirement':'Below requirement';
 const spare=d.limit-d.exposure;
 const common=`capital-card ${gap<0?'shortfall':''}`;
 const parts=[{label:'CET1',value:d.cet1,color:'#18528b'},{label:'AT1',value:d.at1,color:'#4d9ee3'}];
 const min=Math.min(0,d.exposure>0?d.cet1/d.exposure:0);
 const max=Math.max(.07,d.target*1.2,Number.isFinite(d.ratio)?d.ratio*1.2:0);
 const y=(n:number)=>330-(n-min)/(max-min)*285;
 const levels=[{label:'Leverage requirement',ratio:d.minimum},{label:'Internal leverage target',ratio:d.target}].sort((a,b)=>b.ratio-a.ratio);
 const grouped=Math.abs(d.target-d.minimum)<1e-10;
 let cumulative=0;
 return <div className="capital-dashboard leverage-dashboard"><div className="capital-cards">
  <section className={common}><header><h3>Leverage ratio</h3><span className="capital-status">{status}</span></header><div className="capital-ratios"><div><strong>{formatPct(d.ratio)}</strong><span>Actual</span></div><div><span>Requirement</span><b>{formatPct(d.minimum)}</b></div><div><span>Headroom</span><b className="capital-gap">{pp(gap)}</b></div></div><Gauge actual={d.ratio} required={d.minimum} target={d.target}/><div className="capital-amounts"><div><b>{formatCurrency(d.tier1)}</b><span>Actual Tier 1 capital</span></div><div><b>{formatCurrency(d.required)}</b><span>Required Tier 1</span></div><div><b className="capital-gap">{signedMoney(d.surplus)}</b><span>Capital headroom</span></div></div><p className="lcr-target">Dotted marker: internal target {formatPct(d.target)}.</p></section>
  <section className={common}><header><h3>Tier 1 capital</h3><span className="capital-status">{status}</span></header><div className="capital-ratios"><div><strong>{formatCurrency(d.tier1)}</strong><span>Actual</span></div><div><span>Requirement</span><b>{formatCurrency(d.required)}</b></div><div><span>Headroom</span><b className="capital-gap">{signedMoney(d.surplus)}</b></div></div><Gauge actual={d.tier1} required={d.required} target={d.exposure*d.target} money/><div className="capital-amounts"><div><b>{formatPct(d.ratio)}</b><span>Actual leverage ratio</span></div><div><b>{formatPct(d.minimum)}</b><span>Required ratio</span></div><div><b className="capital-gap">{pp(gap)}</b><span>Ratio headroom</span></div></div><p className="lcr-target">Dotted marker: Tier 1 at the internal target, {formatCurrency(d.exposure*d.target)}.</p></section>
  <section className={common}><header><h3>Leverage exposure</h3><span className="capital-status">{status}</span></header><div className="capital-ratios"><div><strong>{formatCurrency(d.exposure)}</strong><span>Actual</span></div><div><span>Implied limit</span><b>{formatCurrency(d.limit)}</b></div><div><span>Headroom</span><b className="capital-gap">{signedMoney(spare)}</b></div></div><Gauge actual={d.exposure} required={d.limit} money/><div className="capital-amounts"><div><b>{formatPct(d.ratio)}</b><span>Actual leverage ratio</span></div><div><b>{formatPct(d.minimum)}</b><span>Minimum</span></div><div><b className="capital-gap">{d.exposure>0?formatPct(spare/d.exposure):'N/A'}</b><span>Spare exposure capacity</span></div></div><p className="lcr-target">Implied capacity holds Tier 1 constant. Risk-weighted capital and liquidity constraints may bind sooner.</p></section>
 </div><div className="capital-detail-grid">
  <section className="capital-card"><h3>Tier 1 composition</h3><p className="capital-total">Total Tier 1 held <strong>{formatCurrency(d.tier1)} ({formatPct(d.ratio)})</strong></p>{d.exposure>0?<svg className="capital-composition" viewBox="0 0 740 390" role="img" aria-label={`Tier 1 composition: CET1 ${formatCurrency(d.cet1)}, AT1 ${formatCurrency(d.at1)}; exposure ${formatCurrency(d.exposure)}. Requirement ${formatPct(d.minimum)}, internal target ${formatPct(d.target)}.`}>{[0,1,2,3,4].map(i=>{const n=min+(max-min)*i/4;return <g key={i}><path d={`M65 ${y(n)}H350`} stroke="var(--border)"/><text x="55" y={y(n)+5} textAnchor="end">{formatPct(n,1)}</text></g>;})}<text transform="translate(18 180) rotate(-90)" textAnchor="middle">% of leverage exposure</text>{parts.map(p=>{const start=cumulative;cumulative+=p.value/d.exposure;const top=y(Math.max(start,cumulative)),height=Math.abs(y(start)-y(cumulative));return <g key={p.label}><rect x="110" y={top} width="190" height={height} fill={p.color}/>{height>40&&<text x="205" y={top+height/2} textAnchor="middle" className="stack-label">{p.label}<tspan x="205" dy="21">{formatCurrency(p.value)} ({formatPct(p.value/d.exposure)})</tspan></text>}</g>;})}{(grouped?levels.slice(0,1):levels).map((l,i)=><g key={l.label}><path d={`M300 ${y(l.ratio)}H345L385 ${150+i*85}H400`} fill="none" stroke={l.label.startsWith('Internal')?'#b24b92':'#7956bd'} strokeWidth="2" strokeDasharray={l.label.startsWith('Internal')?'2 4':'6 4'}/><text x="410" y={145+i*85}>{grouped?'Requirement & internal target':l.label}<tspan x="410" dy="24" fontWeight="700">{formatPct(l.ratio)} · {formatCurrency(l.ratio*d.exposure)}</tspan></text></g>)}<text x="205" y="375" textAnchor="middle" fontWeight="700">Leverage exposure {formatCurrency(d.exposure)}</text></svg>:<p>Ratio composition is unavailable without positive leverage exposure.</p>}<ul className="capital-legend">{parts.map(p=><li key={p.label}><i style={{background:p.color}}/>{p.label} · {formatCurrency(p.value)}</li>)}</ul></section>
  <section className="capital-card"><h3>Requirement breakdown</h3><table><thead><tr><th>Item</th><th>Ratio / value</th></tr></thead><tbody><tr><th>Model leverage requirement</th><td>{formatPct(d.minimum)}</td></tr><tr><th>Additional leverage buffers</th><td>Not modelled</td></tr><tr className="total-row"><th>Total model requirement</th><td>{formatPct(d.minimum)}</td></tr></tbody></table><p className="muted">The model uses the configured leverage requirement. Additional leverage buffers are not separately modelled.</p><table><tbody>{[['Total leverage exposure',formatCurrency(d.exposure)],['Required Tier 1 capital',formatCurrency(d.required)],['Actual Tier 1 capital',formatCurrency(d.tier1)],['Surplus Tier 1 capital',signedMoney(d.surplus)],['Internal target',formatPct(d.target)],['Tier 1 at internal target',formatCurrency(d.target*d.exposure)],['Headroom to internal target',signedMoney(d.tier1-d.target*d.exposure)]].map(([label,value])=><tr key={label}><th>{label}</th><td>{value}</td></tr>)}</tbody></table></section>
 </div><section className="capital-card leverage-reconciliation"><h3>Leverage exposure reconciliation</h3><table><thead><tr><th>Contribution</th><th>Amount</th></tr></thead><tbody>{d.exposureRows.map(r=><tr key={r.label}><th>{r.label}</th><td>{r.value<0?'−':''}{formatCurrency(Math.abs(r.value))}</td></tr>)}</tbody><tfoot><tr><th>Total leverage exposure</th><td>{formatCurrency(d.exposure)}</td></tr></tfoot></table></section><section className="capital-card capital-history"><h3>Leverage ratio over time</h3><div style={{height:270}}><TimeSeriesChart data={history.map(s=>({step:s.time.step,value:s.risk.riskMetrics.leverageRatio}))} xLabel="Month" yLabel="Leverage ratio (%)"/></div></section></div>;
}
