import { useState } from 'react';
import { BankState } from '../domain/bankState';
import { periodHistory } from '../game/management';
import { mandateProgress, quarterlyReviews } from '../game/boardroom';
import { formatCurrency, formatPct } from '../utils/formatters';
export default function PerformanceReport({history}:{history:BankState[]}) {
 const [period,setPeriod]=useState(3);
 const periods=periodHistory(history,period),latest=periods.at(-1),prior=periods.at(-2);
 const progress=mandateProgress(history),reviews=quarterlyReviews(history);
 return <div className="stack"><section className="card history-card"><div className="section-heading"><div><div className="eyebrow">The bank you are building</div><h2>Watch the strategy develop</h2></div><div className="department-tabs">{[3,12].map(n=><button className={`button ${period===n?'primary':''}`} key={n} aria-pressed={period===n} onClick={()=>setPeriod(n)}>{n===3?'Quarters':'Years'}</button>)}</div></div>
   {periods.length===0?<div className="history-empty"><strong>Your story starts here.</strong><p>Set a policy in a department, then run a quarter. You will see earnings accumulate and the funding base develop. You can pause after any month.</p></div>:<><div className="profit-timeline" aria-label="Profit by reporting period">{periods.slice(-12).map(p=><div className="profit-period" key={p.label}><span>{formatCurrency(p.profit)}</span><div className="profit-track"><div className={p.profit<0?'negative':''} style={{height:`${Math.max(4,Math.abs(p.profit)/Math.max(1,...periods.slice(-12).map(x=>Math.abs(x.profit)))*60)}px`}}/></div><strong>{p.label}</strong><small>{p.months<period?`${p.months}/${period} months`:'Complete'}</small></div>)}</div><p className="muted">{latest&&latest.months<period?'The current period is incomplete. Compare it with a full period only after the books close.':prior?`Profit changed by ${formatCurrency(latest!.profit-prior.profit)} from the previous period.`:'Your first completed period establishes the baseline.'}</p>
   <details><summary>View period figures and closing balances</summary><div className="table-scroll"><table className="data-table"><thead><tr><th>Period</th><th>Months</th><th>Profit</th><th>Deposits</th><th>CET1</th></tr></thead><tbody>{periods.map(p=><tr key={p.label}><td>{p.label}</td><td>{p.months}/{period}</td><td>{formatCurrency(p.profit)}</td><td>{formatCurrency(p.deposits)}</td><td>{formatPct(p.cet1)}</td></tr>)}</tbody></table></div></details></>}
  </section>  <details className="card"><summary>Optional first-year board challenges · {progress.stars}/3 stars</summary><p>The bank continues after year one. These badges record your opening year without changing money or capital.</p><div className="quarterly-reviews">{reviews.map(r=><article key={r.quarter}><strong>Q{r.quarter} · {r.title}</strong><p>{r.detail}</p><span>{r.complete?r.earned?'★ Earned':'Missed':r.active?'In progress':'Upcoming'}</span></article>)}</div>{progress.objectives.map(o=><p key={o.label}>{o.achieved?'✓':'○'} {o.label}: {o.detail}</p>)}</details></div>;
}
